defaults:
  - _self_
  - gpt2model: gpt2-small

_target_: mamba_ssm.models.mixer_seq_simple.MambaLMHeadModel
_recursive_: True
config:
  _target_: mamba_ssm.models.MambaConfig
  reorder_and_upcast_attn: false
  scale_attn_by_inverse_layer_idx: true
  n_positions: ${datamodule.max_length}
